export type Story = {
  title: string;
  sentences: [string, string, string, string];
  blanks: { sentence: number; answer: string; options: [string, string, string] }[];
};

export const stories: Story[] = [
  { title: "A cup of tea", sentences: ["Maya filled the kettle with fresh water.", "She placed a tea bag in her favorite mug.", "She poured in the hot water and waited.", "Then she sat by the window with her warm tea."], blanks: [{ sentence: 0, answer: "kettle", options: ["kettle", "toaster", "basket"] }, { sentence: 1, answer: "mug", options: ["plate", "mug", "bowl"] }, { sentence: 3, answer: "window", options: ["door", "shelf", "window"] }] },
  { title: "Breakfast time", sentences: ["Leo washed an apple before breakfast.", "He toasted two slices of bread.", "He spread butter on each slice.", "He drank a glass of milk at the table."], blanks: [{ sentence: 0, answer: "apple", options: ["apple", "orange", "pear"] }, { sentence: 1, answer: "bread", options: ["cheese", "bread", "rice"] }, { sentence: 3, answer: "milk", options: ["juice", "water", "milk"] }] },
  { title: "A walk in the park", sentences: ["Nina put on her walking shoes.", "She took a bottle of water with her.", "She followed the path beside the trees.", "She rested on a bench near the pond."], blanks: [{ sentence: 0, answer: "shoes", options: ["gloves", "shoes", "socks"] }, { sentence: 1, answer: "bottle", options: ["basket", "bottle", "book"] }, { sentence: 3, answer: "bench", options: ["bridge", "gate", "bench"] }] },
  { title: "Watering the plants", sentences: ["Sam filled a watering can at the sink.", "He carried it to the sunny room.", "He poured water into the plant pots.", "Then he wiped a few drops from the floor."], blanks: [{ sentence: 0, answer: "watering can", options: ["watering can", "teapot", "bucket"] }, { sentence: 2, answer: "pots", options: ["plates", "pots", "cups"] }, { sentence: 3, answer: "floor", options: ["table", "wall", "floor"] }] },
  { title: "At the grocery shop", sentences: ["Ava wrote a short list before leaving.", "She put carrots and beans in her basket.", "She chose a loaf of bread from the shelf.", "At home, she placed the food in the kitchen."], blanks: [{ sentence: 0, answer: "list", options: ["map", "list", "letter"] }, { sentence: 1, answer: "basket", options: ["basket", "drawer", "box"] }, { sentence: 2, answer: "bread", options: ["cake", "bread", "cereal"] }] },
  { title: "A quiet reading time", sentences: ["Iris chose a book from the shelf.", "She found a chair beside the lamp.", "She read a story about a small boat.", "She put a bookmark between the pages."], blanks: [{ sentence: 0, answer: "book", options: ["book", "pillow", "glass"] }, { sentence: 2, answer: "boat", options: ["train", "boat", "plane"] }, { sentence: 3, answer: "bookmark", options: ["key", "ribbon", "bookmark"] }] },
  { title: "Cleaning a room", sentences: ["Omar opened the curtains to let in light.", "He put his clothes into the cupboard.", "He swept the floor with a broom.", "He made the bed with a clean sheet."], blanks: [{ sentence: 0, answer: "curtains", options: ["curtains", "drawers", "doors"] }, { sentence: 2, answer: "broom", options: ["brush", "broom", "mop"] }, { sentence: 3, answer: "sheet", options: ["towel", "blanket", "sheet"] }] },
  { title: "Feeding a pet", sentences: ["Ella scooped food into the cat's bowl.", "She filled a second bowl with water.", "Her cat came over and began to eat.", "After lunch, Ella brushed its soft fur."], blanks: [{ sentence: 0, answer: "bowl", options: ["bowl", "box", "bag"] }, { sentence: 2, answer: "cat", options: ["dog", "cat", "bird"] }, { sentence: 3, answer: "fur", options: ["fur", "feathers", "tail"] }] },
  { title: "Visiting a friend", sentences: ["Ben picked a flower from the garden.", "He wrapped it in a piece of paper.", "He walked to his friend's front door.", "They sat together and shared some juice."], blanks: [{ sentence: 0, answer: "flower", options: ["leaf", "flower", "stone"] }, { sentence: 2, answer: "door", options: ["window", "gate", "door"] }, { sentence: 3, answer: "juice", options: ["soup", "juice", "tea"] }] },
  { title: "At the library", sentences: ["Zoe returned her library book.", "She looked along the shelves for a new story.", "She showed her library card at the desk.", "She carried her new book home in a bag."], blanks: [{ sentence: 0, answer: "book", options: ["book", "coat", "plate"] }, { sentence: 2, answer: "card", options: ["coin", "card", "note"] }, { sentence: 3, answer: "bag", options: ["basket", "box", "bag"] }] },
  { title: "Making lunch", sentences: ["Ravi washed a tomato and some lettuce.", "He put them between two slices of bread.", "He cut the sandwich with a small knife.", "He packed lunch in a paper bag."], blanks: [{ sentence: 0, answer: "lettuce", options: ["lettuce", "cereal", "cheese"] }, { sentence: 1, answer: "bread", options: ["bread", "cake", "rice"] }, { sentence: 3, answer: "bag", options: ["jar", "bag", "bowl"] }] },
  { title: "Packing a school bag", sentences: ["Mia checked the list on the table.", "She put her books into her school bag.", "She added a pencil case and a notebook.", "She zipped the bag before going to bed."], blanks: [{ sentence: 0, answer: "list", options: ["list", "sock", "cup"] }, { sentence: 2, answer: "notebook", options: ["notebook", "spoon", "towel"] }, { sentence: 3, answer: "zipped", options: ["washed", "zipped", "opened"] }] },
  { title: "Buying fruit", sentences: ["Noah chose three ripe peaches.", "He added a bunch of yellow bananas.", "The shopkeeper put the fruit in a bag.", "Noah carried it carefully to the car."], blanks: [{ sentence: 0, answer: "peaches", options: ["peaches", "potatoes", "onions"] }, { sentence: 1, answer: "bananas", options: ["lemons", "bananas", "plums"] }, { sentence: 3, answer: "car", options: ["bus", "shop", "car"] }] },
  { title: "An afternoon walk", sentences: ["Luca put on his blue jacket.", "He walked along the quiet street.", "He stopped to watch a bird in a tree.", "He came home before the sun went down."], blanks: [{ sentence: 0, answer: "jacket", options: ["jacket", "hat", "shirt"] }, { sentence: 2, answer: "bird", options: ["bird", "fish", "rabbit"] }, { sentence: 3, answer: "sun", options: ["moon", "lamp", "sun"] }] },
  { title: "Getting ready for class", sentences: ["Sara woke up when her alarm rang.", "She washed her face and brushed her teeth.", "She ate breakfast before getting dressed.", "She took her bag and left for class."], blanks: [{ sentence: 0, answer: "alarm", options: ["alarm", "radio", "clock"] }, { sentence: 1, answer: "teeth", options: ["hands", "teeth", "hair"] }, { sentence: 3, answer: "bag", options: ["bag", "coat", "book"] }] },
];

export const storyBuilderLevel = { level: 1, sentences: 4, blanks: 3, optionsPerBlank: 3, timed: false } as const;
